import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Result from '../components/Result'
import Request from '../utils/Request'
import 'tailwindcss/tailwind.css'
export default function Home(props) {
  console.log(props)
  return (
    <div>
      <Head>
        <title>Hullo 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Header></Header>
         <Nav></Nav>
         <Result results={props.results}></Result>

   </div>
  )
}



export async function getServerSideProps(context){
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${Request[genre]?.url || Request.fetchTrending.url}`)
  .then((res)=>res.json())
  return {
    props:{
      results : request.results,
    },
  }

}
